# Generated by Django 5.0.4 on 2026-07-06 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CredentialType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique short code (e.g., TOR, COE).', max_length=10, unique=True)),
                ('name', models.CharField(help_text='Full name of the credential type.', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of the credential.')),
                ('price', models.DecimalField(decimal_places=2, help_text='Fixed price for this credential.', max_digits=10)),
                ('processing_days', models.PositiveIntegerField(help_text='Estimated processing time in days.')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this credential type is currently offered.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
