# Generated by Django 5.0.4 on 2026-07-06 06:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CredentialRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('REQUIREMENTS_VERIFICATION', 'Requirements Verification'), ('REQUIREMENTS_REJECTED', 'Requirements Rejected'), ('PAYMENT_PENDING', 'Payment Pending'), ('PAYMENT_VERIFIED', 'Payment Verified'), ('PROCESSING', 'Processing'), ('READY_FOR_RELEASE', 'Ready for Release'), ('RELEASED', 'Released'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=50)),
                ('tracking_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credential_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='credentials.credentialtype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credential_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='credentials_status_3cb47b_idx'), models.Index(fields=['user'], name='credentials_user_id_e2cd60_idx'), models.Index(fields=['tracking_number'], name='credentials_trackin_fdac5b_idx')],
            },
        ),
    ]
