# Generated by Django 5.0.4 on 2026-07-06 08:39

import credentials.models
import credentials.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0002_credentialrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequirementDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(help_text='Type of document (e.g., ID, CLEARANCE).', max_length=50)),
                ('file', models.FileField(upload_to=credentials.models.document_upload_path, validators=[credentials.validators.validate_file_size, credentials.validators.validate_file_extension, credentials.validators.validate_mime_type])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='credentials.credentialrequest')),
            ],
        ),
    ]
