# Generated by Django 5.0.4 on 2026-07-06 09:10

import credentials.models
import credentials.validators
import django.core.files.storage
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0003_requirementdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirementdocument',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location=pathlib.PureWindowsPath('D:/RALPH_PROGRAMMING/capstone/backend/private_media')), upload_to=credentials.models.document_upload_path, validators=[credentials.validators.validate_file_size, credentials.validators.validate_file_extension, credentials.validators.validate_mime_type]),
        ),
    ]
