# Generated by Django 5.0.4 on 2026-07-14 07:41

import credentials.models
import credentials.storage
import credentials.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0005_studentclearance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirementdocument',
            name='file',
            field=models.FileField(storage=credentials.storage.PrivateMediaStorage(), upload_to=credentials.models.document_upload_path, validators=[credentials.validators.validate_file_size, credentials.validators.validate_file_extension, credentials.validators.validate_mime_type]),
        ),
        migrations.AlterField(
            model_name='studentclearance',
            name='file',
            field=models.FileField(storage=credentials.storage.PrivateMediaStorage(), upload_to=credentials.models.clearance_upload_path, validators=[credentials.validators.validate_file_size, credentials.validators.validate_file_extension, credentials.validators.validate_mime_type]),
        ),
    ]
