# Generated by Django 5.0.4 on 2026-07-26 15:24

import credentials.models
import credentials.storage
import credentials.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0006_alter_requirementdocument_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('receipt_reference_number', models.CharField(blank=True, max_length=100)),
                ('receipt_image', models.FileField(storage=credentials.storage.PrivateMediaStorage(), upload_to=credentials.models.receipt_upload_path, validators=[credentials.validators.validate_file_size, credentials.validators.validate_file_extension, credentials.validators.validate_mime_type])),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=50)),
                ('remarks', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='credentials.credentialrequest')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
