# Generated by Django 5.0.4 on 2026-07-05 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='The action performed (e.g., CREATE_REQUEST, VERIFY_PAYMENT)', max_length=255)),
                ('object_type', models.CharField(help_text='The model name of the object being modified', max_length=100)),
                ('object_id', models.CharField(help_text='The primary key of the object being modified', max_length=255)),
                ('previous_state', models.JSONField(blank=True, help_text='State of the object before the action', null=True)),
                ('new_state', models.JSONField(blank=True, help_text='State of the object after the action', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('metadata', models.JSONField(blank=True, help_text='Optional contextual metadata', null=True)),
                ('actor', models.ForeignKey(blank=True, help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
