# Generated by Django 5.0.4 on 2026-07-14 05:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('ACCOUNT_CREATED', 'Account Created'), ('PASSWORD_RESET', 'Password Reset'), ('REQUEST_CREATED', 'Request Created'), ('REQUEST_STATUS_CHANGED', 'Request Status Changed'), ('CLEARANCE_SUBMITTED', 'Clearance Submitted'), ('CLEARANCE_APPROVED', 'Clearance Approved'), ('CLEARANCE_REJECTED', 'Clearance Rejected')], max_length=50)),
                ('message', models.TextField()),
                ('related_object_type', models.CharField(blank=True, max_length=100, null=True)),
                ('related_object_id', models.CharField(blank=True, max_length=255, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
