# Generated by Django 5.0.4 on 2026-07-30 10:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_notificatio_user_id_05b4bc_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_user_id_f2ad08_idx',
        ),
        migrations.AlterField(
            model_name='notification',
            name='event_type',
            field=models.CharField(choices=[('ACCOUNT_CREATED', 'Account Created'), ('PASSWORD_RESET', 'Password Reset'), ('REQUEST_CREATED', 'Request Created'), ('REQUEST_STATUS_CHANGED', 'Request Status Changed'), ('CLEARANCE_SUBMITTED', 'Clearance Submitted'), ('CLEARANCE_APPROVED', 'Clearance Approved'), ('CLEARANCE_REJECTED', 'Clearance Rejected'), ('PAYMENT_SUBMITTED', 'Payment Submitted'), ('PAYMENT_VERIFIED', 'Payment Verified'), ('PAYMENT_REJECTED', 'Payment Rejected')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx'),
        ),
    ]
